name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main                 # Branch principal

permissions:
  contents: write          # Permite gravar no gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci          # ou yarn install --frozen-lockfile

      - name: Build website
        run: npm run build  # gera a pasta `build`

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
